"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/mainComponents/Navbar'
import Footer from '../components/mainComponents/Footer'
import { Provider } from "react-redux";
import { persistor ,store } from '../store/store'
import { PersistGate } from "redux-persist/integration/react";
 import { ToastContainer, toast } from 'react-toastify';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <Navbar />
            <PersistGate loading={null} persistor={persistor}>
            {children}
          </PersistGate>

          <ToastContainer />
        </Provider>
        <Footer/>
      </body>
    </html>
  );
}
